"""membuat tabel photo ondelete

Revision ID: 0cfdd7d96587
Revises: df12ac3d08e7
Create Date: 2024-04-21 17:16:53.195685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cfdd7d96587'
down_revision = 'df12ac3d08e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo_item', schema=None) as batch_op:
        batch_op.drop_constraint('photo_item_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customer', ['customer_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('photo_item_ibfk_1', 'customer', ['customer_id'], ['id'])

    # ### end Alembic commands ###
