"""memberi kolom process yang hilang

Revision ID: 7d26c139d502
Revises: f2da65f46c64
Create Date: 2024-04-22 09:12:07.469368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d26c139d502'
down_revision = 'f2da65f46c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('process', sa.Integer(), nullable=False))
        batch_op.alter_column('url',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('process')

    # ### end Alembic commands ###
