"""menghapus kolom url customer

Revision ID: 99023fc1cd39
Revises: 0d2b02870b3b
Create Date: 2024-04-22 08:58:12.823241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99023fc1cd39'
down_revision = '0d2b02870b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('process')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('process', mysql.VARCHAR(length=120), nullable=False))

    # ### end Alembic commands ###
