"""membuat tabel customer

Revision ID: df9f780ad388
Revises: e49d2234630a
Create Date: 2024-04-21 15:21:07.391521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df9f780ad388'
down_revision = 'e49d2234630a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_product', sa.String(length=255), nullable=True))
        batch_op.drop_index('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index('address', ['address'], unique=True)
        batch_op.drop_column('photo_product')

    # ### end Alembic commands ###
